### ISSUE TITLE
Variant pathogenicity

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2783] opened 2022-06-13 12:56 UTC
**Describe the bug**
A variant marked as one-star pathogenic in seqr, is actually benign per Clinvar. There are currently no records in Clinvar indicating it is pathogenic. It is possible the path entry was deleted from Clinvar, but seqr has not been updated to reflect this change. Submitting a ticket just to make sure this is not a bug. 

**Link to page(s) where bug is occurring**
seqr page - https://seqr.broadinstitute.org/variant_search/variant/11-31789912-CT-C/family/F030436_kan_1456

Clinvar page - https://www.ncbi.nlm.nih.gov/clinvar/variation/1278291/?oq=1017445[alleleid]&m=NM_001368894.2(PAX6):c.*21del%20(p.Ter437=)

**Scope of the bug**
Likely variant specific.

**Screenshots**
<img width="1215" alt="Screen Shot 2022-06-13 at 8 56 07 AM" src="https://user-images.githubusercontent.com/37872186/173358614-ada1953f-a07f-4f61-a3f1-9e757337ee28.png">
<img width="1231" alt="Screen Shot 2022-06-13 at 8 56 27 AM" src="https://user-images.githubusercontent.com/37872186/173358630-c1ccfc3c-a9bd-4f9e-84cf-4e2b13b447fe.png">

**Comment by lynnpais** [comment] 2022-06-13 13:26
I came across another example where a variant appears as one-star pathogenic in seqr, but is one-star benign per ClinVar. ClinVar also noted that the Most recent submission was in Oct 4, 2021. Again, not sure if a bug or seqr ClinVar info has not been updated in the last 6 months. 
Case - https://seqr.broadinstitute.org/variant_search/variant/1-152306292-G-GCC/family/F030435_kan_1461
ClinVar entry - https://www.ncbi.nlm.nih.gov/clinvar/variation/1301631/?oq=1019163[alleleid]&m=NM_002016.2(FLG):c.8590_8591del%20(p.His2864fs)

**Comment by hanars** [comment] 2022-06-13 16:18
Clinvar is only updated for projects when they are reloaded, and data has not been loaded to this project since June 2021. In recently loaded projects these variants are correctly annotated as benign/likely benign, and if we reloaded the data for this project that would fix the issue but would be something you would need to reach out to the loading team to have done. 

I am unclear why there is no record in clinvar that these variants were ever pathogenic, but that is a question for the clinvar team. I asked in slack so you can follow there to see if anyone has any insight. But regardless, this is not a bug in seqr so I will be close this issue out. Thank you for reporting though, this was definitely worth looking into

**Closed by hanars** 2022-06-13 16:18 UTC
Labels: bug

**Comment by lynnpais** [comment] 2022-06-13 18:17
It didn't seem like an obvious seqr but since there was no record of
previous ClinVar entries for the variants, I couldn't be sure. As you said,
it is really weird that ClinVar doesn't track this stuff. Thanks for
posting in Slack!
