### ISSUE TITLE
Unable to load saved variants page for RGP_79

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3874] opened 2024-02-12 15:47 UTC
**Describe the bug**
Clicking the saved variants bar opens a blank page for family RGP_79. 

**Link to page(s) where bug is occurring**
Family page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F019327_rgp_79
Saved variants blank page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F019327_rgp_79

**Scope of the bug**
Only happening in this family at the moment.

**Comment by hanars** [comment] 2024-02-12 16:35
This is actually a duplicate of this other issue, it was found in another family too: https://github.com/broadinstitute/seqr/issues/3866
Closing this one out so we can track work in one place

FWIW, this affects families that have manual SVs

**Closed by hanars** 2024-02-12 16:35 UTC
Labels: bug
