### ISSUE TITLE
Intronic variants returned when not selected 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2878] opened 2022-08-11 13:25 UTC
**Describe the bug**
Intronic variants returned even when the annotation has been unselected. It does not have a SpliceAi score >0.1 so there's no reason I can think of why it should be overriding a filter, if that's the underlying issue. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/e2d5d18661acb8762089e9a761cd7093?page=1&sort=in_omim

**Scope of the bug**
Across all cases in seqr. 

**Screenshots**
<img width="1236" alt="Screen Shot 2022-08-11 at 9 21 22 AM" src="https://user-images.githubusercontent.com/37872186/184143634-8b6d5555-47d7-4e38-b41e-107fbbba5309.png">

<img width="1287" alt="Screen Shot 2022-08-11 at 9 21 40 AM" src="https://user-images.githubusercontent.com/37872186/184143643-ba28b373-33d4-4db6-8a41-ec91c98f771a.png">

**Comment by hanars** [comment] 2022-08-16 20:18
Seqr search filters variants based on ANY of the VEP annotated consequence for a transcript, but only shows the worst consequence for each transcript. In the GGPS1 variant in your search, transcript ENST00000642503 is annotated by vep as both "intron_variant" and "NMD_transcript_variant". Since you are allowing NMD_transcript_variant in your search, the variant is being returned. But since seqr only shows one consequence per transcript, it looks like that transcript is just an intron variant.

You only see this sort of behavior when you specify that you want a "less bad" consequence but the transcript with that consequence also has a worse consequence you didn't ask for. This seems to be not so common for the high and medium impact consequences we generally  use in search but does appear to be the case with intronic transcripts.

I am closing this out as it is not a bug, all of the returned variants do have a transcript that is annotated as one of the "better than intronic" consequences. However, it would be very easy to update the detailed transcript display to show all the consequences for each transcript and not just the worse one, so feel free to make a ticket for that if you want. You would, however, need to click into the transcript details to see it, there isn't really a way to show a secondary consequence for a given transcript in the variant summary

**Closed by hanars** 2022-08-16 20:18 UTC
Labels: bug
