### ISSUE TITLE
cannot upload a vcf file to seqr

### ISSUE THREAD

**Issue by anatopf** [broadinstitute/seqr#4108] opened 2024-05-22 23:04 UTC
cannot upload a vcf file to seqr from Terra/Anvil

[**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...](https://seqr.broadinstitute.org/create_project_from_workspace/GSD_IranWES/GSD_IranWES)

**Scope of the bug**
have not tried other projects

**Screenshots**

![image](https://github.com/broadinstitute/seqr/assets/68847177/97bde241-9e0f-4a96-a557-0ccc9018fc41)

**Comment by hanars** [comment] 2024-05-23 14:27
Please provide a full screenshot of the page where this error is occurring, not just the error message.

**Comment by anatopf** [comment] 2024-05-23 14:36
Thanks for getting back to me!
Unfortunately, I cannot provide the screenshot as seqr is not letting me log in either now

I am trying to log in using google, but the page keeps re-loading and nothing happens

https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?client_id=733952080251-ah0nd6if5kp6ee90r3nif7aeldr1htq5.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fseqr.broadinstitute.org%2Fcomplete%2Fgoogle-oauth2%2F&state=SyNY8vHjxUecibLH6FggBwuzn8QYuELI&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20openid&access_type=offline&approval_prompt=auto&service=lso&o2v=1&ddm=0&flowName=GeneralOAuthFlow

[cid:4cb47053-7a60-4d63-9870-7d6153fb9422]

Ana Töpf, PhD
Senior Research Associate
John Walton Muscular Dystrophy Research Centre


[cid:078645e4-b4a2-41c2-9092-aa23cf2a1842][cid:8a620403-08ed-4b4f-b787-aca305f51090]   [cid:4929c250-b703-4605-9786-22a6f51842ea]
________________________________

**Comment by hanars** [comment] 2024-05-28 15:38
duplicate of https://github.com/broadinstitute/seqr/issues/4112

**Closed by hanars** 2024-05-28 15:38 UTC
Labels: bug
