### ISSUE TITLE
Variant search page very slow

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4241] opened 2024-07-17 14:49 UTC
**Describe the bug**
Similar to #4238, the dropdown on the variant page for inheritance is taking >20 secs. Happened thrice. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/family/F020795_rgp_289

**Scope of the bug**
Noticed in RGP, but haven't tried other projects

**Screenshots**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9wQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f55ec206f1d98fe3e6b25d7cf578153921ecadb/Screenshot%202024-07-17%20at%2010.47.35%E2%80%AFAM.png" alt="Screenshot 2024-07-17 at 10.47.35 AM.png" />

**Comment by hanars** [comment] 2024-07-17 17:58
this is the same backend functionality on different pages, so its a duplicate of #4238

**Closed by hanars** 2024-07-17 17:58 UTC
Labels: bug
