### ISSUE TITLE
Variant GQ

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1353] opened 2020-06-23 20:19 UTC
**Describe the bug**
The GQ filter is set to 20, but there are variants with 'no' GQ that are appearing in the search. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/4-38014723-G-GCCGC/family/F027952_vcgs_fam209
and
https://seqr.broadinstitute.org/variant_search/variant/4-87615917-T-G/family/F027952_vcgs_fam209

**Scope of the bug**
Currently seeing it in the VCGS exomes project

**Screenshots**

![Screen Shot 2020-06-23 at 4 18 26 PM](https://user-images.githubusercontent.com/37872186/85456679-3694b700-b56d-11ea-88b9-dc7d531b05ac.png)

![Screen Shot 2020-06-23 at 4 18 58 PM](https://user-images.githubusercontent.com/37872186/85456733-42807900-b56d-11ea-9192-fa034c9d5d9b.png)

**Comment by hanars** [comment] 2020-06-25 15:35
Hi Lynn, when you are reporting a bug with search you need to include a link to the actual search page where the bug is occurring, not just to the variants

**Comment by lynnpais** [comment] 2020-07-30 13:39
Hi Hana,

Here's a link to the search and results - https://seqr.broadinstitute.org/variant_search/results/53a1eae6e865a3ed277e297b0c388996?page=1&sort=xpos

Let me know if there's anything else you need.

Thanks!

**Comment by hanars** [comment] 2020-07-30 16:21
@mike-w-wilson it looks like null values for `gq`and `ab` are making it through the pipeline - for example I see a lot of similar entries under `genotypes`, ad then these sample ids are not being properly added to the `samples_gq_0_to_5` field so they aren;t being filtered
```
{
     "num_alt": 0,
     "gq": null,
     "ab": null,
     "dp": 34,
     "sample_id": "VCGS_FAM209_641_D1"
},
``` 

I can look into a fix for this, but I was wondering if this was intentional for any reason

**Comment by mike-w-wilson** [comment] 2020-08-03 14:30
@hanars , this was not intentional. We were changing any `nul` field in the vcf to `.` in the sharded vcf pre-loading but I believe DSP changed their delivery format to unsharded recently. Our current pipeline does not do any checks on VCF format so that should probably change to catch the issues before they are loaded.

**Comment by hanars** [comment] 2020-08-03 15:13
I would say this is a relatively high priority fix, given that it causes lots of noisey results to come back from search. Do you have the time to get this change in, or should I try to figure it out?

**Comment by mike-w-wilson** [comment] 2020-08-03 17:51
Sorry, after looking into the code this looks to be intended behavior initially but the nulls don't seem to be considered downstream during the sample gq/ab range buckets for ES export. https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/42ddf5e5105f600786c3a4c4fd105676ec6d8ab3/luigi_pipeline/lib/model/seqr_mt_schema.py#L248 is where the null is created and then the GT field bucket ranges get built here https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/42ddf5e5105f600786c3a4c4fd105676ec6d8ab3/luigi_pipeline/lib/model/seqr_mt_schema.py#L222 I'm not sure why nulls are being included since the bucketing starts at 0?

**Comment by hanars** [comment] 2020-08-03 19:02
Theres 2 fields: `genotypes` which stores the raw value of everything and has the nulls and the bucketing fields i.e. `samples_gq_0_to_5`, which currently has nothing in it. The problem is the way seqr filters is it says "don't return any variant where the sample id is in `samples_gq_0_to_5`" so we are getting all these shitty calls returned because they aren't being filtered out. I think this was an error in what we chose as the default, it should be 0 not null. Is there a reason not to make that change?

**Comment by mike-w-wilson** [comment] 2020-08-03 19:51
I cannot think of any reason to not make the change. I can make a PR for this.

**Comment by mike-w-wilson** [comment] 2020-08-03 21:10
Ok so after talking to @ch-kr, the GQ should not be set to null since `is_called` is true in these cases. I ended up looking into the matrixtable from this projects most recent loading session and found the GQ was set to NA. 
<img width="1011" alt="v15_vcgs_gq_na" src="https://user-images.githubusercontent.com/15892871/89227561-e832f900-d5ab-11ea-9e22-2bd1dde8d983.png">
This seems like a bug from DSP. The next version, the GQ for the same site is 99.
<img width="1018" alt="v16_vcgs_gq_99" src="https://user-images.githubusercontent.com/15892871/89227593-f7b24200-d5ab-11ea-8f04-c9f4bfe1243e.png">
So in the present code I think we want to keep the null whenever GT is not called but we may want to add a check for GQ being NA? or any entry field being NA when GT is called?

**Comment by hanars** [comment] 2020-08-03 21:48
Hmm so maybe we should track down the bug of why it was NA in the first place if it was called?

**Comment by hanars** [comment] 2021-01-12 19:52
@mike-w-wilson did we ever resolve this?

**Comment by hanars** [comment] 2021-04-12 18:19
data reloading appears to have fixed this issue

**Closed by hanars** 2021-04-12 18:19 UTC
Labels: bug
