### ISSUE TITLE
Unable to assign an analyst to a case

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4163] opened 2024-06-13 17:30 UTC
**Describe the bug**
Unable to assign an analyst to a case

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0555_seqr_demo/family_page/F031959_demofamily1

**Scope of the bug**
Across internal and external AnVIL projects. 

**Screenshots**
<img width="741" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ba677769bdbf8f0a56850200660088223d650a8/Screenshot%202024-06-13%20at%201.29.04%E2%80%AFPM.png" alt="Screenshot 2024-06-13 at 1.29.04 PM.png" />

**Comment by jklugherz** [comment] 2024-06-13 18:37
I tracked the bug down to a terra api refresh token failure https://github.com/broadinstitute/seqr/blob/master/seqr/views/utils/terra_api_utils.py#L118 and found warning logs: https://cloudlogging.app.goo.gl/DKYdDAq2YiuoNcEeA

**Comment by lynnpais** [comment] 2024-06-14 00:10
I think this might be related to permissions and not a bug. I am able to assign cases in the RGP and not any others.

**Comment by hanars** [comment] 2024-06-14 14:18
you should not be assigning cases in the public demo project. This is a feature not a bug

**Comment by lynnpais** [comment] 2024-06-18 15:11
As discussed, I am unable to assign an analyst to a case in any other project other than RGP. For example - https://seqr.broadinstitute.org/project/R0312_cmg_bonnemann_genomes/family_page/F015974_uc223 when I select the dropdown, I do not see names of other users who have access to the project.

**Comment by hanars** [comment] 2024-06-18 16:08
So there is a fundamental limit here because seqr does not store the list of people who have access to a project, thats stored in AnVIL and only users with the "can share" permission are allowed to see the list of users with access from AnVIL,  and that is not something we can change. What we can do is allow users to assign *themselves* to cases. This means that manager-level individuals with the "can share" permission can assign anyone to cases, and everyone else can assign themselves to cases but not other people, which feels like a reasonable compromise

**Comment by hanars** [comment] 2024-06-20 15:01
this is now fixed

**Closed by hanars** 2024-06-20 15:01 UTC
Labels: bug
